syntax = "proto3";

package zeish.cloud.control.v1;

message SecretsRequest {
  string organization_id = 6;
  string secret_id = 1;
  string sandbox_id = 2;
  string grant_id = 3;
  string json = 4;
  string operation = 5;
}

message SecretsResponse {
  string json = 1;
}

service SecretsService {
  rpc ListSecrets(SecretsRequest) returns (SecretsResponse);
  rpc GetSecret(SecretsRequest) returns (SecretsResponse);
  rpc CreateSecret(SecretsRequest) returns (SecretsResponse);
  rpc UpdateSecret(SecretsRequest) returns (SecretsResponse);
  rpc DeleteSecret(SecretsRequest) returns (SecretsResponse);
  rpc GrantSecret(SecretsRequest) returns (SecretsResponse);
  rpc MintSecretLease(SecretsRequest) returns (SecretsResponse);
  rpc ListSandboxSecretGrants(SecretsRequest) returns (SecretsResponse);
  rpc GrantSandboxSecret(SecretsRequest) returns (SecretsResponse);
  rpc RevokeSandboxSecret(SecretsRequest) returns (SecretsResponse);
}
